# Generated by Django 4.1.7 on 2023-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('news', 'News'), ('ads', 'Ads')], default='news', max_length=250),
        ),
    ]
