# Generated by Django 4.1.7 on 2023-08-15 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0004_alter_category_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryNews',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostNews',
        ),
    ]
