# Generated by Django 4.1.7 on 2023-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_rename_category_categorynews_rename_post_postnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynews',
            name='title',
            field=models.CharField(choices=[('news', 'Новости'), ('ads', 'Реклама')], default='news', max_length=250),
        ),
        migrations.AlterField(
            model_name='postnews',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
    ]
