# Generated by Django 4.1.7 on 2023-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_retraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
