# Generated by Django 4.1.7 on 2023-08-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_retraining', '0002_alter_program_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryProfRetrain',
        ),
        migrations.RenameModel(
            old_name='Program',
            new_name='ProgramProfRetrain',
        ),
    ]
