# Generated by Django 4.1.7 on 2023-09-15 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_retraining', '0003_rename_category_categoryprofretrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprofretrain',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
