# Generated by Django 4.2.6 on 2023-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_retraining', '0005_alter_categoryprofretrain_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryprofretrain',
            options={'ordering': ['pk']},
        ),
    ]
