# Generated by Django 4.2.6 on 2023-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_retraining', '0006_alter_categoryprofretrain_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprofretrain',
            name='audience_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryprofretrain',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryprofretrain',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
