# Generated by Django 4.1.7 on 2023-08-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_training', '0004_alter_program_code_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='app_prof_training.category'),
        ),
    ]
