# Generated by Django 4.1.7 on 2023-08-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_training', '0005_alter_program_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryProfTrain',
        ),
        migrations.RenameModel(
            old_name='Program',
            new_name='ProgramProfTrain',
        ),
    ]
