# Generated by Django 4.1.7 on 2023-09-25 09:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_training', '0009_alter_categoryproftrain_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programproftrain',
            name='document',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('certificate', 'Свидетельство об обучении'), ('book', 'Удостоверение')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programproftrain',
            name='hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
