# Generated by Django 4.1.7 on 2023-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_training', '0010_programproftrain_document_programproftrain_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproftrain',
            name='audience_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryproftrain',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryproftrain',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
