# Generated by Django 4.1.7 on 2023-09-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_training', '0011_categoryproftrain_audience_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programproftrain',
            name='code_num',
            field=models.CharField(max_length=50),
        ),
    ]
