# Generated by Django 4.2.6 on 2023-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_training', '0012_alter_programproftrain_code_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproftrain',
            options={'ordering': ['pk']},
        ),
    ]
