# Generated by Django 4.2.6 on 2023-10-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0002_alter_tutor_options_tutor_subject_tutor_vk_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('work_experience', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
