# Generated by Django 4.2.6 on 2023-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0003_becometutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
