# Generated by Django 4.2.6 on 2023-10-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutor', '0004_alter_tutor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becometutor',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
