# Generated by Django 4.1.7 on 2023-08-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductEco',
        ),
    ]
