# Generated by Django 4.1.7 on 2023-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecology', '0002_rename_product_producteco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteco',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
