# Generated by Django 4.1.7 on 2023-07-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0003_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
