# Generated by Django 4.1.7 on 2023-07-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0004_alter_program_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
