# Generated by Django 4.1.7 on 2023-08-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0005_alter_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryProfDev',
        ),
        migrations.RenameModel(
            old_name='Program',
            new_name='ProgramProfDev',
        ),
    ]
