# Generated by Django 4.1.7 on 2023-09-15 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0007_alter_categoryprofdev_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprofdev',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
