# Generated by Django 4.1.7 on 2023-09-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0009_categoryprofdev_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='programprofdev',
            name='document',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
