# Generated by Django 4.1.7 on 2023-09-19 11:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0012_alter_programprofdev_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programprofdev',
            name='document',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('certificate_prof_dev', 'Удостоверение о повышении квалификации'), ('protocol', 'Протокол проверки знаний'), ('certificate', 'Удостоверение о проверке знаний')], max_length=200, null=True),
        ),
    ]
