# Generated by Django 4.1.7 on 2023-09-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0013_alter_programprofdev_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='programprofdev',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
