# Generated by Django 4.1.7 on 2023-09-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0014_programprofdev_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprofdev',
            name='audience_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoryprofdev',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
