# Generated by Django 4.1.7 on 2023-09-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0015_categoryprofdev_audience_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprofdev',
            name='audience_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
