# Generated by Django 4.1.7 on 2023-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prof_dev', '0016_alter_categoryprofdev_audience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprofdev',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
