# Generated by Django 4.1.7 on 2023-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab_prot', '0003_rename_product_productlabprot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlabprot',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
